name: Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Check for updates
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          latest_version="$(gh release view -R FIRST-Tech-Challenge/scorekeeper --json tagName --jq '.tagName[1:]')"
          latest_channel="$(curl -sSfL "$(gh release view -R FIRST-Tech-Challenge/scorekeeper --json body --jq '(.body | match("(https://[^ >\n]*)")).captures[0].string')" | grep -F window.channelToken | sed -e 's/^.*window\.channelToken = "\([^"]*\)".*$/\1/')"
          current_version="$(grep -o '^ARG VERSION=[0-9]\+\.[0-9]\+\.[0-9]\+$' Dockerfile | head -n1 | sed -e 's/^ARG VERSION=//')"
          today="$(date +'%Y-%m-%d')"

          [ -n "$latest_version" ] || (echo 'failed to check latest version' >&2; exit 1)

          if [ ! "$latest_version" = "$current_version" ]; then
            sed -i -e 's/^ARG VERSION=[0-9]\+\.[0-9]\+\.[0-9]\+$/ARG VERSION='"$latest_version"'/' Dockerfile
            sed -i -e 's/^ARG CHANNEL=\w\+$/ARG CHANNEL='"$latest_channel"'/' Dockerfile
            sed -i -e 's/^ARG BUILD_DATE=[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}$/ARG BUILD_DATE='"$today"'/' Dockerfile
          fi

      - id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update_ftclive_action
          delete-branch: true
          committer: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          commit-message: 'container: update FTCLive release'
          title: 'container: update FTCLive release'
          labels: 'dependencies'
          body: |
            Automated bump of FTCLive release

      - uses: benc-uk/workflow-dispatch@v1
        if: ${{ contains(fromJSON('["created", "updated"]'), steps.create-pr.outputs.pull-request-operation) }}
        with:
          workflow: deploy.yml
          ref: refs/heads/update_ftclive_action
